version: '3.3'

services:
  db:
    image: postgres
    env_file:
      - .dbenv
    restart: unless-stopped

  web:
    image: docker.gensosekai.com/cv:latest
    env_file:
      - .webenv
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped
