version: '3.3'

services:
  db:
    image: postgres
    env_file:
      - .dbenv
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped

  web:
    image: docker.gensosekai.com/conveyerui:latest
    env_file:
      - .webenv
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:

